### ISSUE TITLE
Network card for ESXi 7.0.0

### ISSUE THREAD

**Issue by token47** [canonical/packer-maas#1]
Hi!

I'm trying to generate esxi 7 images and it fails because of no supported network card is found. So far I discovered the following:

1) the e1000 driver support is dropped in esxi 7. In fact, I tested every single one of all the cards supported by qemu and none of them is supported in ESXi 7 anymore (except for vmxnet3 -- see below). If you try to generate an image of the v7 the installation aborts very early in the process complaining that there is no supported network card plugged in the system.

2) qemu supports, to my surprise, the vmxnet3 virtual network card (could not find documentation for this but if you do a "qemu -device help" you can see it listed there.

3) ESXi is happy with seeing a vmxnet3 card on the "hardware". This is for scenarios where it is running nested. Not sure if this is officially supported in production but it works nice, I have used it in the lab even on prior versions.

Anyway, I tried changing the network type for 'vmxnet3' and it's not working. It does not complain about missing network cards anymore and goes on with the installation, but it just freezes when trying to fetch the kickstart image over http, which makes me think the network is not really working.

I'm wondering if there is any other thing I can do to make it work.

**Comment by token47** [comment]
On a slightly different question but still trying to solve the same problem: would re-creating the iso with the kickstart embedded help? Or attaching it to the VM on a second virtual block device?

**Comment by token47** [comment]
There must be something fishy on the qemu side with the vmxnet3 because I cannot make it work even on vSphere 6.5 or vSphere 6.7. A bunch of tutorials on the internet explain that it works so I'm not sure what is missing. It could be the default for all versions of vSphere if it worked.

**Comment by token47** [comment]
Ok, I managed to get a vSphere 7 image doing the following:

1) change the network type to "vmxnet3" so it will not complain about missing nic hardware

2) remove the kickstart line and proceed manually trough the installation (using the VNC interface)

Image was generated successfully.

This does not really fix the actual problem, though.

**Comment by token47** [comment]
I discovered that there is a 'e1000e' card (Intel i82547L) supported by qemu that _is_ supported by ESXi 7.0.0 and also earlier versions, so this one is a huge candidate to be the default for the maas packer templates.

Problem is that packer itself does not support it (!!!). Packer does check the network card type against an internal list when parsing the json and gives an error of unsupported card type because 'e1000e' is not on that list. I re-built packer with that driver added and it worked, so we should probably open a bug there for this.

Anyway, the installation worked ok for ESXi 6.5 and 6.7, but is also giving me trouble on 7.0 (I can see with tcpdump that the GET request for the kickstart file gets truncated and the webserver replies with error. Something is fishy on the ESXi 7.0 side, probably.

Anyway, I embedded the KS file inside the ISO image, changed the boot parameters to " ks=cdrom:/KS.CFG<enter>" and it worked, image for v7 was built and works good for provisioning (right now have a 10 nodes cluster privisioned by maas on v7).

There's probably not much that can be done here, from what I see, but I would like to hear comments on this.

**Comment by ltrager** [comment]
Thanks for the bug report. I will be looking at ESXi 7.0 support in the next few weeks. VMware ESXi isn't meant to be run in virtual environments which is why vmxnet3 may not be working. The Packer template configures qemu to emulate real hardware to get around that. It does look like the e1000 driver has been removed from ESXi 7.0. [A commit was recently added to Packer which allows any qemu network driver to be used.](https://github.com/hashicorp/packer/commit/b0c7fe491c9923f81fb5630105d4feb5b22d91f8) When I tried e1000e with VMware 6.7 it reported the system has no network devices.

Completing the install manually or rerolling the ISO are both good work arounds. I'll be looking into getting VMware ESXi 7.0 install fully automated.

**Comment by token47** [comment]
I'm pretty positive that e1000e is supported on earlier versions, this can be checked on the online HCL. In fact, I installed a 6.7 with e1000e. About vmxnet3, ESXi has support for running nested in itself (this is not supported in production but is officially supported in the HCL for building labs). In fact it works, ESXi boots, finds the vmxnet3 (does not complain anymore about missing ethernet hardware) but there must be some corruption going on because the HTTP GET for the KS do not finish (you can see it starting in tcpdump).

Please let me know if I can help test any new idea.

**Comment by ltrager** [comment]
It seems that there are [multiple networking issues with ESXi networking, qemu, and Packer](https://github.com/hashicorp/packer/issues/9156). The e1000 driver has been removed and neither the vmxnet3 nor the e1000e drivers are working with ESXi 7.0 The kickstart file in packer-maas contains a start up script which runs the MAAS scripts that configure storage, networking, and complete the installation. Respinning the the ISO to contain the kickstart file seems to be the easiest way forward. I'll keep an eye on what upstream is doing to see if I can get network install working again.

**Comment by token47** [comment]
Yes, I had a feeling that the problems were tied to the user network, because I have seen both e1000e and vmxnet3 drivers working otherwise. Both work to the point of being detected and letting the installation to proceed but both have some kind of corruption when sending data out.

Inserting the KS in the ISO worked for me, for now. I also had to use vmxnet3 or e1000e drivers for the installer not to complain about missing a supported network card.

Beware when doing that, you MUST specify capital letters on the ks name on the iso image, even if case should not matter. ks=cdrom:/KS.CFG works while ks=cdrom:/ks.cfg does not. And it's just not obvious at all.

**Comment by rgl** [comment]
Packer 1.6.0 will have support for using a bridge instead of a user-mode network. ESXi 7 will work when the VM uses a bridge and a vmxnet3 nic. I'm doing that at [rgl/esxi-vagrant](https://github.com/rgl/esxi-vagrant).

**Comment by hansbogert** [comment]
> Packer 1.6.0 will have support for using a bridge instead of a user-mode network. ESXi 7 will work when the VM uses a bridge and a vmxnet3 nic. I'm doing that at [rgl/esxi-vagrant](https://github.com/rgl/esxi-vagrant).

Though not with packer-maas, we hit the same problem. The solution only partly applies, vmxnet + bridge networking works in our case as well; however, only in legacy bios mode. In UEFI, the network stack  with vmxnet3 seems to not work at all. Though the nic is found and set correctly.

**Comment by brunobernardi** [comment]
Hello everyone,

I've been testing the image for ESXI 7.0, adjusting the vmware-esxi.json file as mentioned in the commit https://github.com/canonical/packer-maas/pull/8/commits/dc7f97cbcdad897bf7296ecdd2bf72d448dd316e.

However, I have the following error when deploying:

==> qemu: Error getting the bridge virbr0 interface: route ip + net: no such network interface

Has anyone experienced this error?

**Comment by rhtyd** [comment]
With vmxnet3 I see packet retransmissions, it's not usable; with e1000e it's unstable as well.

**Comment by ltrager** [comment]
8541e55ff3f537e244d258ad579c5417c1ea949f modifies the VMware ESXi packer template to provide the kickstart file via an ISO image generated by Packer. This removes the need for using networking at all when generating the image. A vmxnet3 device is provided during the installation as the installer fails if no network card is detected.

This allows packer-maas to be used with a VMware ESXi 7.0 ISO. In the coming weeks I'll be testing all MAAS features with VMware ESXi 7.0. Right now it looks like configuring datastores may not be working and I still need to test vCenter integration.
