### ISSUE TITLE
Packer Custom Images fail to build with Ubuntu Template

### ISSUE THREAD

**Issue by stephenandary** [canonical/packer-maas#117]
```
==> cloudimg.image.qemu.cloudimg (shell-local): /tmp/packer-shell3798110126: line 4: ../scripts/setup-nbd: No such file or directory
Build 'cloudimg.image.qemu.cloudimg' errored after 15 minutes 43 seconds: 1 error(s) occurred:

* Post-processor failed: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
```
Whether using base configuration, or passing custom configuration for the Ubuntu Packer template, I keep hitting this error and I am not sure why. 

I have installed all the requirements and even installed Ubuntu instead of using Manjaro.

Is there supposed to be a setup-nbd script in the scripts directory?

When I grep I get: 

```
rg setup-nbd
ubuntu-flat.pkr.hcl
62:      "source ../scripts/setup-nbd",

ubuntu-cloudimg.pkr.hcl
119:      "source ../scripts/setup-nbd",
```

But I have no setup-nbd script in the scripts directory.

**Comment by alexsander-souza** [comment]
the script is in the shared `scripts` dir in the root of the repository. 
How are you calling packer? are you using the makefile?

**Comment by stephenandary** [comment]
I can't recall anymore as it has been some time. I may have tried both, but I can't be certain. 

I am new to MAAS so it is more probable user error on my part. 

When I loop back around to working with this again in the future I can verify and update this issue.

**Comment by stephenandary** [comment]
@alexsander-souza, looks like I wasn't using a Makefile. Thank you for pointing that out! Will close this issue now. Thanks for the help!
