### ISSUE TITLE
Uploading image not possible?

### ISSUE THREAD

**Issue by Dinosurr** [canonical/packer-maas#14]
The command in the README for centos8 errors that the command doesnt exist?

`maas $PROFILE boot-resources create name='centos/8-custom' title='CentOS 8 Custom' architecture='amd64/generic' filetype='tgz' content@=centos8.tar.gz`

`argument COMMAND: invalid choice: 'boot-resources' (choose from 'login', 'logout', 'list', 'refresh', 'root')`

**Comment by fenar** [comment]
you need to perform maas login so your upload operation would be authorized.

**Comment by ltrager** [comment]
$PROFILE is a shell variable. As @fenar mentioned you must login first. [Please see the MAAS documentation for how.](https://maas.io/docs/maas-cli)
