### ISSUE TITLE
ESXI images fail to build under Mantic (kubuntu)

### ISSUE THREAD

**Issue by ghadi-rahme** [canonical/packer-maas#149]
Tested using packer `1.9.4`
When trying to build an ESXI 7U3 image using the `make -ISO=<path to esxi iso>` command, the build process runs for a few minutes before exiting with an error. 
The build process used to work without errors when my machine was running Lunar. 

The output from packer can be found below:
[packer-logs.txt](https://github.com/canonical/packer-maas/files/12929645/packer-logs.txt)

**Comment by SK1Y101** [comment]
Can verify the same issues are seen at CI.
from the looks of things, the image archive was built, but was not returned. Something in the post-processor failed, alongside the initial issue with building wheel.

**Comment by alexsander-souza** [comment]
the python error is related to the local environment.
