### ISSUE TITLE
packer-maas should clean machine-id automatically after customization

### ISSUE THREAD

**Issue by token47** [canonical/packer-maas#150]
If you customize an ubuntu image using packer-maas, no matter what you do after the customization you need to clean the image, specially the machine-id of systemd for it to be a proper golden image. If you don't, it will generate an image that contains an initialized /etc/machine-id. That machine-id will be used in all deployed hosts and will create many problems with duplicated mac addresses and other issues that depend on that id being unique.

It is easy to do it yourself at the end of your customization script, but this being a vital step it is something that should be done by packer-maas itself and not rely on the user. This step could be added as a default on option to clean whatever is good practice cleaning before shutting down to take the image snapshot.

**Comment by krembu** [comment]
@token47  @alexsander-souza  we just discover that same issue appear on building rhel8/9 images

**Comment by troyanov** [comment]
Hi @krembu 
It was fixed and merged https://github.com/canonical/packer-maas/pull/179

**Comment by krembu** [comment]
@troyanov fix was applied only for ubuntu, rhel family still suffer from this issue
