### ISSUE TITLE
"disk_interface": "ide" doesn't work in packer 1.6.3 - 1.6.5

### ISSUE THREAD

**Issue by tomkivlin** [canonical/packer-maas#17]
https://github.com/canonical/packer-maas/blob/adce21d943addc9944fc06d681cecc90a2f33311/vmware-esxi/vmware-esxi.json#L19

As per https://github.com/hashicorp/packer/issues/10211 on the packer repository, this option breaks qemu.

**Comment by ltrager** [comment]
According to the linked bug this should be fixed with Packer 1.6.6. VMware ESXi does not support virtio disks so this option is required.

**Comment by tomkivlin** [comment]
for info, using packer v1.6.2 is fine and this all works fine.  e.g. https://releases.hashicorp.com/packer/1.6.2/packer_1.6.2_linux_amd64.zip
