### ISSUE TITLE
Rocky8 can't install htop?

### ISSUE THREAD

**Issue by derekcat** [canonical/packer-maas#186]
Hey!
This may be a minor thing, but per the included Extras repo line at the top of the Kickstart file, we should have access to EPEL packages during Kickstart package install, correct?

I was able to install everything else I wanted, but htop still causes the build to fail.

Tried adding in `dnf install` lines for both epel-release and htop, but that didn't work either.

Thoughts?

**Comment by lwandrebeck** [comment]
I'd bet you need some dnf update after after installing epel-release so dnf knows epel  packages list.
HTH

**Comment by derekcat** [comment]
Hey @lwandrebeck I tried these in the `%post` section:
```
dnf -y install epel-release
dnf makecache
dnf -y install htop 
```
That should make it cache the source correctly, yes?

Also if I understand correctly, the line at the top:
```
repo --name="Extras" --mirrorlist="https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=extras-8" ${KS_PROXY}
```
Should already enable EPEL packages, correct?

**Comment by lwandrebeck** [comment]
Makecache should do the trick.
I don't think (to check) that Extras will enable epel though.

**Comment by derekcat** [comment]
Hmmm curious..  Yeah it just hung and produced a ~3.5KB tar.gz output when I tried those.
Is doing the `dnf -y install epel-release` the normal way to get EPEL packages in kickstart?  Maybe that needs to fire in a different section?

**Comment by lwandrebeck** [comment]
Can’t tell for sure as I don’t use kickstart but I doubt that would be different from a classical hand-made or automated install.
