### ISSUE TITLE
Ephemeral deployments only supported on Ubuntu Bionic 18.04+

### ISSUE THREAD

**Issue by darkopetrovic** [canonical/packer-maas#187]
Hello,

I'm trying to deploy with MAAS a custom ubuntu image build from the template on a **diskless** machine, but got the following error:

`Ephemeral deployments only supported on Ubuntu Bionic 18.04+`

I've tested the following images:

```
make custom-cloudimg.tar.gz
make custom-ubuntu.tar.gz
make custom-ubuntu-lvm.dd.gz
make custom-ubuntu-lvm.dd.gz SERIES=bionic
```

but for all of them the same error.

Note that this error occurs when I select the image from the **Custom** OS list.

When I select the image from the **Ubuntu** OS list, the error is: `Action failed for 1 machine: tidy-ewe`. 

Looking in the logs (`/var/log/maas/regiond.log`), I can see the following error:

```
maasserver.websockets.handlers.machine: [error] Bulk action (deploy) for cba6kq failed: custom/ubuntuimg-tgz is not a supported operating system and release combination.
```

So it seems that the name given to the image when uploaded matters here. 

When I test a different name, like `ubuntu/custom-1`: I get:

`maasserver.websockets.handlers.machine: [error] Bulk action (deploy) for cba6kq failed: custom-1 has no kernels available.`

When I try an image build for example with `-var kernel=linux-lowlatency`, I get the same: 

`maasserver.websockets.handlers.machine: [error] Bulk action (deploy) for cba6kq failed: custom-2 has no kernels available.`

Not sure that I'm doing right here thought. I'm quite new to this topic.

---

Is there something particular we can do to build an image from the template for a diskless machine? Can we even do that or is it limited to official Ubuntu releases? Because deploying the default Ubuntu image provided by MAAS on that diskless machine **is working** as excepted!

I'm using MAAS version 3.4.0.

**Comment by r00ta** [comment]
Hi @darkopetrovic , 

MAAS 3.4 can't deploy custom images ephemerally.

MAAS 3.5 (will be released in the next months) introduces the ability to deploy custom images ephemerally. If you have the chance to play with 3.5 (you can use the snap channel latest/edge), could you please give it a try and report back if you still have issues?

**Comment by darkopetrovic** [comment]
thanks @r00ta for this relevant information. 

I'm on a testing machine so I certainly can do that, but I have to figure out how I can update maas to 3.5 because I've installed it from packages. I don't know if I need to uninstall first ans install freshly from snap. 

Anyway, entering the holidays period. Coming back next year for a feedback.
