### ISSUE TITLE
How to create custom partitions of the root disk for ubuntu

### ISSUE THREAD

**Issue by devahariharan** [canonical/packer-maas#199]
Hi, 
I'm new to packer and trying to create a custom ubuntu image. I'm able to successfully build the image, but need assistance with how to create this root partitions as per the requirement.

**Comment by gsperry2011** [comment]
I'm not sure I understand your requirements but this sounds like something you would configure on the node and not do within your custom image.

**Comment by alexsander-souza** [comment]
Hi @devahariharan, the partitioning of the disk is a task done by MAAS during the deployment. 
(unless you are building a dd-raw image, which should be used only in some very special scenarios)

**Comment by alexsander-souza** [comment]
please go to https://discourse.maas.io/ for general discussion about packer-maas and maas.
