### ISSUE TITLE
error build centos 8

### ISSUE THREAD

**Issue by coccolesto** [canonical/packer-maas#2]
hi, 
my sistem is ubuntu 18.04 with maas 2.7. Istalled all required packages (qemu-utils + packer), dowload packer-maas-master and unzip in my home dir, then cd to centos8 dir and run

max@jolly:~/packer-maas-master/centos8$ sudo packer build centos8.json
qemu output will be in this color.

1 error(s) decoding:

* cannot parse 'disk_size' as uint: strconv.ParseUint: parsing "4G": invalid syntax

**Comment by ltrager** [comment]
Packer has changed its template format. Packer-MAAS uses the latest format which works with Packer 1.5.x. This version isn't available in the Ubuntu archive and must be [downloaded from Packer.io](https://www.packer.io/downloads.html). We are looking into creating a Snap for the latest version.
