### ISSUE TITLE
Deploying VMWare ESXi leave machine in "Deploying" state

### ISSUE THREAD

**Issue by ra-albrecht** [canonical/packer-maas#202]
I really like the template for deploying ESXi machines, it works very well and helps a lot.

One problem I have: When done the machine stays in the status "Deploying" instead of switching to "Deployed" state. So I think there is a hook call missing. This is a bit confusing and not correct.

Any idea how to solve this?

Tested with Vmware ESXi 8.0U2 image.

**Comment by ra-albrecht** [comment]
Note: Tested with ESXi 7.0, too - same behavior.

**Comment by gsperry2011** [comment]
FWIW I use MAAS to deploy ESXi 7.0 without issues.

Does your ESXi system being deployed have connectivity on the network? Might also want to ensure it has valid DNS servers so it can resolve hostnames (unsure if it is trying to reach the MAAS server via IP or hostname).
