### ISSUE TITLE
MAAS stucks on reboot ESXI machine

### ISSUE THREAD

**Issue by brunobernardi** [canonical/packer-maas#21]
Hello everyone!

We have a problem with the deployment of the vmware-esxi image to maas. We are using the installation script created by canonical and available in the packer-maas repository.

We were able to create and deploy it on a machine on maas, but it freezes in the step of rebooting the machine.

The operating system is installed, accessible and the reboot is completed, however the status of "rebooting" remains in the maas, thus preventing the completion of the deployment.

Could you please help?

Evidence:
![Screenshot from 2021-01-06 16-47-51](https://user-images.githubusercontent.com/77075421/103813533-00b5ac80-503f-11eb-9814-da6d8d6f1e98.png)

**Comment by ltrager** [comment]
Machines need to be able to access MAAS to complete the deployment process. When an operating system is being installed MAAS uses DHCP to boot into the ephemeral environment. At the end of installation network configuration is applied to the target system and the machine reboots. If that network configuration doesn't allow communication with MAAS the machine will be available but MAAS will have no way to know the deployment finished.

You can verify your network configuration is valid by using network testing in MAAS.

**Comment by brunobernardi** [comment]
ltrager, thanks!

Viewing through the esxi interface, at the first start, the esxi goes up without an ip, not taking the ip provided by maas.

Do you believe that this cannot be related to the ks.cfg made available for creating the image?

**Comment by kaiworkmode** [comment]
Hi all, I am also facing the same issue where after deployment of ESXi, the status in maas remains "rebooting". Just want to check what are the steps to resolve the network configuration? Thank you.

**Comment by brunobernardi** [comment]
Hi @kaiworkmode!

I've been encountering this problem for a while, using version 6.5 of ESXi and failing to solve this problem. Therefore, I believe that there is some limitation in the canonical script packer for ESXi 6.5 images.

As version 6.5 is in close EOF, I focused on deployments for ESXi 6.7 and 7.0 images and I had no problems. The scripts work very well for these images and versions 6.7 and 7.0 are more complete and stable than 6.5.

Regards.

**Comment by kaiworkmode** [comment]
Hi @brunobernardi, thanks for getting back. 

Yes, I was having issue with ESXi 6.5 and upon checking further, I realized that it was due to missing drivers in that image.
I then tried ESXi 6.7 with the required drivers and the deployment is successful.

Thanks!

**Comment by artcancrotp** [comment]
I am finding the same problem with ESXi 8.0.1 and I believe I know why it's happening, but I don't know how to fix it.

During deployment, the machine is registered to MaaS DHCP using the MAC address of the NIC.  After installation completes and it reboots into its target operating system, the management interface of the host no longer uses the MAC address of the NIC -- it uses a virtual MAC address, and so the DHCP server gives it a different IP address.  As a result, MaaS does not recognize it as the same machine, and the installation never completes.

If this tickles anyone's existing knowledge of how this is supposed to work, let me know and we'll develop a solution.
