### ISSUE TITLE
Test images locally before deploying to MAAS

### ISSUE THREAD

**Issue by darkopetrovic** [canonical/packer-maas#210]
I have already built and deployed successfully an image to maas. 

What I am trying to do now is to build a custom image and to test it locally before deploying to maas, to check rapidly if the customization is working and to learn about the process. 

Is it possible to start the image locally? Maybe with `qemu-system-x86_64` ?

I tried with `qemu-system-x86_64` but when the image boots it say "No bootable device.".

`qemu-system-x86_64 -m 2G -drive file=custom-cloudimg.tar.gz,format=raw`

---

I tested another packer script from here: https://github.com/skatolo/actuated-packer-qemu

This latter start correctly with:

`qemu-system-x86_64 -m 2G -drive file=jammy.qcow2,format=qcow2`

---

I am new on the topic and I don't yet understand the issue here. I am certainly missing something. Thanks for  the help.

**Comment by emccormickva** [comment]
I'm wondering this as well. I think I'm just not understanding the boot process / order from MaaS properly, but it would be great to spin up a custom image in raw KVM or Openstack or whatever and see what came out the other end of the sausage maker.

**Comment by alexsander-souza** [comment]
While you *can* mimic the steps MAAS does and make this image boot in a local VM, I feel like this is going to be a lot more work than simply installing MAAS in a VM and using it to deploy the image to a local LXD.
