### ISSUE TITLE
Alma8 & Alma 9

### ISSUE THREAD

**Issue by bashadude** [canonical/packer-maas#224]
Hi Guys @alexsander-souza @sparkiegeek @niemeyer @ltrager @SK1Y101 
I am tried to build alma 9.2 iso with alma9 packer build was successfully done. While installing OS i m getting alma 9.3 not alma 9.2. It was updating automatically. Can you please give me solution to stop update blw alma 9.2 -9.3.

**Comment by SK1Y101** [comment]
We build from the latest ISO, ie:
```hcl
variable "alma_iso_url" {
  type    = string
  default = "https://repo.almalinux.org/almalinux/8/isos/x86_64/AlmaLinux-8-latest-x86_64-boot.iso"
}
```

This variable is not currently exposed to the MAKEFILE, but you can pass it if you run packer directly

**Comment by bashadude** [comment]
> We build from the latest ISO, ie:
> 
> ```terraform
> variable "alma_iso_url" {
>   type    = string
>   default = "https://repo.almalinux.org/almalinux/8/isos/x86_64/AlmaLinux-8-latest-x86_64-boot.iso"
> }
> ```
> 
> This variable is not currently exposed to the MAKEFILE, but you can pass it if you run packer directly

Thanks For Quick reply @SK1Y101 

I changed the line in hcl which you sent. In Makefile I added export packer_log=1;. I ran but i m going into the error. please let me know if had to change checksum from 9 to 8.



![image](https://github.com/canonical/packer-maas/assets/56496610/61f0346c-5747-41ad-8741-30a3794cf8fa)

**Comment by SK1Y101** [comment]
Can you verify for me the change you made?
and yes, if you're downloading from https://repo.almalinux.org/almalinux/9.2/isos/x86_64/AlmaLinux-9.2-x86_64-boot.iso, you will need the corresponding checksum: https://repo.almalinux.org/almalinux/9.2/isos/x86_64/CHECKSUM

**Comment by bashadude** [comment]
I changed in alma9.pkr.hcl file
![image](https://github.com/canonical/packer-maas/assets/56496610/3c06bd24-1436-410c-9b20-8026f5528caa)

then i got this
![image](https://github.com/canonical/packer-maas/assets/56496610/5e4312f2-8b50-446c-85fd-cf2b714edfb4)

**Comment by bashadude** [comment]
> Can you verify for me the change you made? and yes, if you're downloading from https://repo.almalinux.org/almalinux/9.2/isos/x86_64/AlmaLinux-9.2-x86_64-boot.iso, you will need the corresponding checksum: https://repo.almalinux.org/almalinux/9.2/isos/x86_64/CHECKSUM
> 
> Downloading the default checksum, it only has references to the latest, which is where at least one issue stems from:
> 
> ```
> # AlmaLinux-9.3-x86_64-boot.iso: 942669824 bytes
> SHA256 (AlmaLinux-9.3-x86_64-boot.iso) = af5377a1d16bbe599ea91a8761ad645f2f54687075802bdc0c0703ee610182e9
> # AlmaLinux-9.3-x86_64-dvd.iso: 10916724736 bytes
> SHA256 (AlmaLinux-9.3-x86_64-dvd.iso) = 4a8c4ed4b79edd0977d7f88be7c07e12c4b748671a7786eb636c6700e58068d5
> # AlmaLinux-9.3-x86_64-minimal.iso: 1860173824 bytes
> SHA256 (AlmaLinux-9.3-x86_64-minimal.iso) = 6624593b53c89195f7b68b2070a280d47b4276a7cbc10d2216661bf35d4f442b
> # AlmaLinux-9-latest-x86_64-boot.iso: 942669824 bytes
> SHA256 (AlmaLinux-9-latest-x86_64-boot.iso) = af5377a1d16bbe599ea91a8761ad645f2f54687075802bdc0c0703ee610182e9
> # AlmaLinux-9-latest-x86_64-dvd.iso: 10916724736 bytes
> SHA256 (AlmaLinux-9-latest-x86_64-dvd.iso) = 4a8c4ed4b79edd0977d7f88be7c07e12c4b748671a7786eb636c6700e58068d5
> # AlmaLinux-9-latest-x86_64-minimal.iso: 1860173824 bytes
> SHA256 (AlmaLinux-9-latest-x86_64-minimal.iso) = 6624593b53c89195f7b68b2070a280d47b4276a7cbc10d2216661bf35d4f442b
> ```

> I changed in alma9.pkr.hcl file ![image](https://private-user-images.githubusercontent.com/56496610/316470154-3c06bd24-1436-410c-9b20-8026f5528caa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjMwOTUsIm5iZiI6MTcxMTM2Mjc5NSwicGF0aCI6Ii81NjQ5NjYxMC8zMTY0NzAxNTQtM2MwNmJkMjQtMTQzNi00MTBjLTliMjAtODAyNmY1NTI4Y2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEwMzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOGM3MjVjZWIxYjZmZDhlYzE5ZTJiOTc5MTI0Njg1ODIzMjYxMmIwYzMyNjVmNjNmZGM3YWNhODM5Njk0MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5cFXGW7L_6oWMH29dPYsh4YHoDsqLvvxZL_vZtdeA6w)
> 
> then i got this ![image](https://private-user-images.githubusercontent.com/56496610/316470369-5e4312f2-8b50-446c-85fd-cf2b714edfb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjMwOTUsIm5iZiI6MTcxMTM2Mjc5NSwicGF0aCI6Ii81NjQ5NjYxMC8zMTY0NzAzNjktNWU0MzEyZjItOGI1MC00NDZjLTg1ZmQtY2YyYjcxNGVkZmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEwMzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNjdlZDU1ODY3ZTE4MjBkNDZkMGNlZTg5Zjk1NWFmZWFhMDk1YzgyOWUzYTQwY2IzNzdkMDkyOTc1YmVlMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92ytNYB4Yria3MZS1qnmlGj9zMHl6znQK05se60n4XE)

**Comment by bashadude** [comment]
> Can you verify for me the change you made? and yes, if you're downloading from https://repo.almalinux.org/almalinux/9.2/isos/x86_64/AlmaLinux-9.2-x86_64-boot.iso, you will need the corresponding checksum: https://repo.almalinux.org/almalinux/9.2/isos/x86_64/CHECKSUM
> 
> Downloading the default checksum, it only has references to the latest, which is where at least one issue stems from:
> 
> ```
> # AlmaLinux-9.3-x86_64-boot.iso: 942669824 bytes
> SHA256 (AlmaLinux-9.3-x86_64-boot.iso) = af5377a1d16bbe599ea91a8761ad645f2f54687075802bdc0c0703ee610182e9
> # AlmaLinux-9.3-x86_64-dvd.iso: 10916724736 bytes
> SHA256 (AlmaLinux-9.3-x86_64-dvd.iso) = 4a8c4ed4b79edd0977d7f88be7c07e12c4b748671a7786eb636c6700e58068d5
> # AlmaLinux-9.3-x86_64-minimal.iso: 1860173824 bytes
> SHA256 (AlmaLinux-9.3-x86_64-minimal.iso) = 6624593b53c89195f7b68b2070a280d47b4276a7cbc10d2216661bf35d4f442b
> # AlmaLinux-9-latest-x86_64-boot.iso: 942669824 bytes
> SHA256 (AlmaLinux-9-latest-x86_64-boot.iso) = af5377a1d16bbe599ea91a8761ad645f2f54687075802bdc0c0703ee610182e9
> # AlmaLinux-9-latest-x86_64-dvd.iso: 10916724736 bytes
> SHA256 (AlmaLinux-9-latest-x86_64-dvd.iso) = 4a8c4ed4b79edd0977d7f88be7c07e12c4b748671a7786eb636c6700e58068d5
> # AlmaLinux-9-latest-x86_64-minimal.iso: 1860173824 bytes
> SHA256 (AlmaLinux-9-latest-x86_64-minimal.iso) = 6624593b53c89195f7b68b2070a280d47b4276a7cbc10d2216661bf35d4f442b
> ```

@SK1Y101  I downloaded a alma9.2****dvd.iso. Not boot.iso

**Comment by SK1Y101** [comment]
I shared the boot link as that's what we use by default. if the dvd iso works for you go for it, the checksum link for 9.2 includes checksums for all 9.2 images

your images above don't load for me by the way

**Comment by bashadude** [comment]
> I shared the boot link as that's what we use by default. if the dvd iso works for you go for it, the checksum link for 9.2 includes checksums for all 9.2 images
> 
> your images above don't load for me by the way

Thanks @SK1Y101
