### ISSUE TITLE
Debian 10 template

### ISSUE THREAD

**Issue by DjairdaSilva** [canonical/packer-maas#24]
Hello Team, 

I would like to know if we will have a template for Debian 10.

Thanks.

**Comment by vittalpai** [comment]
Plus one.. 

Is there any plan of adding a Template for Debian OS?

**Comment by ltrager** [comment]
We do not have any plans to support Debian currently. One of the issues MAAS has with Debian is MAAS always provides apt repository configuration. MAAS only supports configuring Ubuntu archives. This means MAAS overwrites Debian's archives with Ubuntu's which doesn't work and tends to cause deployments to fail.
[
A few community users on discourse.maas.io have made some progress getting Debian working.](https://discourse.maas.io/t/debian10-fails-on-final-reboot/4486/4)

**Comment by Suertzz** [comment]
That super sad, because we would love to deploy proxmox using maas but we can’t ( proxmox support only debian OS ) ☹️

**Comment by StormYudi** [comment]
super sad +1

**Comment by ntrp** [comment]
Proxmox image support would be amazing in MaaS
