### ISSUE TITLE
ESXi doesn't support "pool" for NTP

### ISSUE THREAD

**Issue by grebennikov** [canonical/packer-maas#28]
Currently the vmware script processes the netplan config and configures ntp with "pool" and "server" patterns (pool with names, server with IP addresses).
ESXi however doesn't support "pool" construct, also "iburst" instruction is unacceptable.
Both pools and servers have to be converted into:

server pool.ntp.org
server 1.1.1.1

**Comment by alexsander-souza** [comment]
already fixed in [12d237d](https://github.com/canonical/packer-maas/commit/12d237d5824e8ac90860fc3b1c9f5bf2ecb3d44d)
