### ISSUE TITLE
Unable to create image

### ISSUE THREAD

**Issue by et-ent** [canonical/packer-maas#30]
I am getting this error after the image has been built.

qemu (shell-local): mount: /tmp/packer-maas-3NMO: special device /dev/nbd11p1 does not exist.

I have tried this with Packer versions 1.6.0 through 1.7.2.  So I am not sure where my issue is.  Currently I am using the CentOS 8.

**Comment by ltrager** [comment]
packer-maas binds the image to an nbd device and mounts it. On Linux images this is used to create the tar.gz for MAAS. It is possible that all current nbd devices are in use. If so try to free one up with `qemu-nbd -d /dev/nbd11`. If your not using nbd devices try unloading the kernel module with `modprobe -r nbd` or rebooting.

If that doesn't work feel free to reopen with any modifications you've made attached.
