### ISSUE TITLE
storage-esxi script and server with more then one disk

### ISSUE THREAD

**Issue by kiruka4** [canonical/packer-maas#34]
Hello.

When I deploy server with only one disk in it everything works fine. But on servers with two or more disks MAAS don’t create any datastores. It successfully deploy ESXi, configure network, register server in the vCenter. But there are no any datastores. I tried to create datastores in UI on both disks, tried leave datastore only on the disk with the system. In both cases there no datastores after deployment. And only when I deleted second disk in the UI, after comissioning, server succsessfully deploed and created datastore.

**Comment by alexsander-souza** [comment]
not reproduced in MAAS 3.3
