### ISSUE TITLE
ESXi 7U2 does not support packer-maas deployment strategy

### ISSUE THREAD

**Issue by cookiesowns** [canonical/packer-maas#35]
Hi Guys,

I was debugging some strange VMFS corruption on hosts that mount a shared lun (iSCSI, or shared disks on Dell VRTX).. it turns out it seems the issue stems from UUID being the same when deploying from the cloned maas install when using via packer.

https://kb.vmware.com/s/article/84349

We may want to look at alternatives, as it seems in 7U2 the workaround that the ks.cfg does in firstboot to re-generate the system UUID does not work for 7U2 and newer systems

**Comment by gamkiller77** [comment]
I will be testing this on 7u3c. It is working for me on 7u2 just fine but i never posted how i fixed it so give me a day to pull that info up.

**Comment by gamkiller77** [comment]
I got it to work the line in the KS file need to be at the bottom and read like this.

`sed -i 's#/system/uuid.*##' /etc/vmware/esx.conf

reboot`

I do a PR and ask for a merge of the changes.  I just tested in my setup and it is working.

**Comment by adarobin** [comment]
@gamkiller77 that is interesting, because that is specifically called out as not working with 7.0 Update 2 and newer in the KB article that @cookiesowns linked to.

In any case, https://kb.vmware.com/s/article/84280 calls out that this deployment method is not supported at all by VMware so I'd be a bit hesitant to use it in production. I wonder if there are any remnants of the original UUID lurking in [`configstorecli`](https://williamlam.com/2021/07/introduction-to-the-new-esxi-configuration-store-cli-configstorecli.html).

**Comment by cookiesowns** [comment]
Exactly,

Those changes will not work. While as a stand-alone host it may be fine, if you do any shared storage with host locking like iscsi, NFS, vSAN, you will slowly start to see file corruption.

**Comment by gamkiller77** [comment]
So I used this on 7.0.3c on my non-prod cluster.  I will check with my support people as I work for VMware.

I built an image checked the UUID and then rebuilt it and the UUID changed.  We are using vSAN and had to do this to get it to work as there was duplicate UUID in our cluster.

**Comment by BrandonMarler** [comment]
Beware that running `esxcfg-info -u` is intended for displaying the hardware uuid. I think people will find that hardware uuid will vary between physical machines but remain the same on a single machine throughout its multiple lifecycles or MAAS deployments.
To verify the "UUID" is changing each time ESXi is deployed, run this after each and compare the results:
`esxcli system uuid get`
which will show the system uuid. Or run
`esxcli storage vmfs extent list`
which will include uuid info for each datastore.

**Comment by AravindhStanley** [comment]
Is this an issue only when the EXSi hosts are booting via Shared Storage, but not if they are booting from directly attached SSD. Or its it going to be a problem even when ESXi are using local SSD for Boot and iscsi for VM Storage?

**Comment by alexsander-souza** [comment]
There's no workaround for this issue, and even if there was one it would not be endorsed by VMWare. 

We are going to limit this image to deployments that don't have any kind shared storage.
