### ISSUE TITLE
The ubuntu image building

### ISSUE THREAD

**Issue by Karolaccount** [canonical/packer-maas#40]
Hello,

While trying to build ubuntu image using `make custom-ubuntu-lvm.dd.gz` the build qemu error `Error finding "http": stat http: no such file or directory` occurs. After create http sample folder next looped issue that occurs is:
```
...
packer-builder-qemu plugin: [INFO] Attempting SSH connection to 127.0.0.1:3173...
packer-builder-qemu plugin: [DEBUG] reconnecting to TCP connection for SSH
packer-builder-qemu plugin: [DEBUG] handshaking with SSH
packer-builder-qemu plugin: [DEBUG] SSH handshake err: Timeout during SSH handshake
...
```
Is this issue already known? Can you give any tips to make it work?
Can be it issue with bad config file in http folder? Can u provide http folder with content for ubuntu (or example http config file)?

Thanks in advance!

**Comment by catycatylee** [comment]
+1

I have the same trouble

**Comment by rohit-karna** [comment]
Hi,

I have the same problem, could anyone kindly let me know how to proceed.
