### ISSUE TITLE
[PATCH] Add Support for Rocky Linux 8

### ISSUE THREAD

**Issue by alanbach** [canonical/packer-maas#44]
Many users have switched from CentOS > Rocky Linux and it may make sense to officially add Rocky Linux 8 support.

What was done:

- Created a profile for Rocky Linux 8
- Generated an image using the latest 8.5 ISO
- Uploaded the image to my local MAAS system
- Successfully Deployed a virtual machine using the uploaded image

Please see the patch attached here:
[rockylinux8-support.patch.gz](https://github.com/canonical/packer-maas/files/8147763/rockylinux8-support.patch.gz)

**Comment by jarrodu** [comment]
I would also like this. I don't know what to do with our patch file, though.

Is that like a pull request?

**Comment by alanbach** [comment]
All you need to do is:

1) Clone this repository.
2) Download the patch file.
3) $ cd packer-maas
4) $ zcat ~/Downloads/rockylinux8-support.patch.gz | patch -p1

And you are all set!

**Comment by alexsander-souza** [comment]
Rocky 8 and 9 are now supported
