### ISSUE TITLE
Centos 7.7

### ISSUE THREAD

**Issue by abduansari** [canonical/packer-maas#45]
I am trying to create centos 7.7 image but it is failing. not able to find the repos for software installation

**Comment by alexsander-souza** [comment]
We are tracking the upstream, which currently points to 7.9

In case you really need to build 7.7, you should to replace all references of `mirrorlist.centos.org` in `http/centos7.ks` with proper 7.7 mirrors, if one still exists. As far as I know 7.7 is deprecated and all official mirrors are gone.
