### ISSUE TITLE
Packer-maas or mass image builder?

### ISSUE THREAD

**Issue by egee-irl** [canonical/packer-maas#6]
I'm interested in building a custom Centos8 image with Snap and other dependencies installed and I've been using this repo but I just discovered [this](https://discourse.maas.io/t/maas-image-builder/1112).

I noticed that the MAAS Image Builder article was written in 2019 but this repo was updated earlier this month.

Is there a "best" or "recommended" path forward? Which method is the official method of building custom MAAS images?

**Comment by ltrager** [comment]
Previously maas-image-builder was the only supported way to build custom images. maas-image-builder is only available to Ubuntu Advantage customers. We decided to transition from using our own tool to using Packer. With this transition we also decided to make MAAS custom image builds free and open source.

Both are still supported however we are focusing future development on packer-maas.

**Comment by sysnasri** [comment]
@ltrager  If I get it correctly you mean maas-image-builder is now free and does not need subscription?
