### ISSUE TITLE
tar-rootfs script is missing from cloudimg directory

### ISSUE THREAD

**Issue by alanbach** [canonical/packer-maas#60]
The tar-rootfs script which is required when building cloud image based custom Ubuntu images is missing from the packer-maas/ubuntu/scripts/cloudimg/ directory. 

Manually copying it from the scripts directory and changing the following lines from:

mount "${nbd}p2" "${TMP_DIR}"
mount "${nbd}p1" "${TMP_DIR}/boot/efi"

To:

mount "${nbd}p1" "${TMP_DIR}"
mount "${nbd}p15" "${TMP_DIR}/boot/efi"

Fixes the issue.

**Comment by sparkiegeek** [comment]
Fixed in #62
