### ISSUE TITLE
Ubuntu cloudimg not working

### ISSUE THREAD

**Issue by crypticsong** [canonical/packer-maas#65]
Running ubuntu-cloudimg.pkr.hcl and getting SSH timeout until the timeout setting in hcl file (set to 45m) and the build fails. Also, tried to open VNC session to see where it is stuck however, not output in VNC.
I am sure you have tested this, but it is not working. Changes I made to the hcl file are : CPU type to base and removed accelerator. 

packer-builder-qemu plugin: [INFO] Attempting SSH connection to 127.0.0.1:2553...
packer-builder-qemu plugin: [DEBUG] reconnecting to TCP connection for SSH
packer-builder-qemu plugin: [DEBUG] handshaking with SSH
packer-builder-qemu plugin: [DEBUG] SSH handshake err: Timeout during SSH handshake

**Comment by alexsander-souza** [comment]
#63 fixes some issues with this template, please try again after this is merged

**Comment by troyanov** [comment]
@crypticsong PR #63 was merged. Can you please try one more time and tell us if the issue still exists?

**Comment by crypticsong** [comment]
Thanks, will give it a try and post the result.

**Comment by crypticsong** [comment]
It is working. Thanks a lot for fixing.
