### ISSUE TITLE
Packer for rhel8 fails

### ISSUE THREAD

**Issue by uberspot** [canonical/packer-maas#69]
Hi, I tried the instructions from here: https://maas.io/docs/how-to-create-custom-images#heading--how-to-pack-a-rhel8-image-for-maas-deployment to build a standard RHEL8.6 image. I made no modifications for anything, ran the kickstart file that you include on a box that has wide-open internet connectivity (no proxies) and full privileges. I specifically installed it for this purpose.

The error with which it fails is: 
![image](https://user-images.githubusercontent.com/237927/188938396-2f4303ac-33e7-46a4-81e2-cb143de618e9.png)

In one of the kickstart steps.
This happened when running packer on both on an ubuntu 20.04 and a 22.04.

```
$ packer version
Packer v1.8.3

$ curtin version
20.1-2-g42a9667f-0ubuntu1~20.04.1

```

Am I doing something wrong? 
The reason I want to pack it is because I wanted to use MaaS to flash some RHEL8 images and pass in custom kernel parameters via maas to point it to different kickstart files on boot. 

I also tried converting the iso to a raw image directly and booting that but we get into these issues: https://discourse.maas.io/t/esxi-deploy-failed-maas-2-9/4670/3 when we try to boot that. Apparently because curtin is missing from the raw image (?). 
Can I manually unpack/repack the iso and just drop curtin/curtin-hooks in there? Is there some example or a place to copy curtin from to do that? 

Thank you in advance.

**Comment by ArpStorm1** [comment]
Hey, happened to me too. Pay attention you need the DVD iso, not the Boot ISO. I've downloaded the Boot ISO by mistake and took me a while to figure it out..

**Comment by vmjfk** [comment]
Hope yours is working now, RHEL 8 worked for me.
