### ISSUE TITLE
ROCKY8 support for maas 3.3.0~beta2

### ISSUE THREAD

**Issue by edvinas31** [canonical/packer-maas#75]
Hi, are rocky8 custom images supported in maas 3.3.0~beta2 version?

This is my setup:
maas: 3.3.0-beta2
postgresql: PostgreSQL 12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
curtin: Version 22.1-0ubuntu1~22.04.1
OS: Ubuntu 22.04

I am asking because I was unable to deploy custom built image. MAAS UI in the logs shows that it is getting timeout on executing "HTTP Request - libutil.c32" event. I thought that it is related with curtin version, but even updating to 22.1 did not actually help and I get the same problem

**Comment by edvinas31** [comment]
Also, I have noticed that https://github.com/canonical/packer-maas/tree/main/rocky8 README.md file says prerequisite is MAAS 3.3 version. Shouldn't it be fixed, because maas 3.3 version is not released yet

**Comment by alexsander-souza** [comment]
Hi @edvinas31, thanks for pointing out the error in the README file. Indeed Rocky is supported out of the box by MAAS since 3.2.1.

About the timeout errors you are facing, can you tell us more about the host being deployed? do you have console access to it in order to see what the bootloader is doing? libutil.c32 is used by grub to boot BIOS-based machines.

**Comment by edvinas31** [comment]
Hi @alexsander-souza we went other way and deployed ROCKY8 as a VM, instead of bare metal machine with MAAS. Regarding the issue we were facing it was probably due to the reason that networking cards in our NIC of a bare metal machine were in need of specific drivers which are not present in rocky8 image. This is of course not 100 % , but we though that we will move on with another solution (using KVM machines on top of ubuntu bare metal)

**Comment by alexsander-souza** [comment]
I'm happy that you found an alternative, but you can add the drivers to the image, see https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#driverdisk
