### ISSUE TITLE
Can packer-maas be used to deploy baremetal?

### ISSUE THREAD

**Issue by ckleu** [canonical/packer-maas#9]
I have tried RHEL and CentOS ISOs, but when I try to deploy them in MAAS the nodes keep ending up with Ubuntu 16.04.
Inspecting the `pxelinux.cfg/01-xxxx` file, it is pointing to:

```
  KERNEL http://[::1]:5248/images/ubuntu/amd64/ga-16.04/xenial/daily/boot-kernel
  INITRD http://[::1]:5248/images/ubuntu/amd64/ga-16.04/xenial/daily/boot-initrd
```

Neither of my CentOS or RHEL scenarios worked. I tried upload under "custom" or "rhel" or "centos" labels
```
packer build centos8-fixed.json
cd output-qemu
tar -czvf centos8-packer-qemu.tar.gz packer-qemu
maas root boot-resources create name='centos/8-custom' title='CentOS 8 Custom' architecture='amd64/generic' filetype='tgz' content@=centos8-packer-qemu.tar.gz
```

**Comment by ltrager** [comment]
MAAS always uses Ubuntu to deploy images. If Ubuntu 16.04 LTS is configured as your commissioning OS it will also be used to deploy any non-Ubuntu operating system.

Packer will generate a MAAS compatible tarball for you, centos8.tar.gz. output-qemu/packer-qemu is a QCOW2 image which is not supported by MAAS.

**Comment by ckleu** [comment]
Currently, we use [cobbler](https://cobbler.github.io/) for baremetal deploys, but MAAS is a lot fast to get machines up-and-ready.
What other tools could be used to deploy cloud-ready/custom images on baremetal with the correct cloud-init fixes? 

OpenStack ironic? [Software Factory](https://softwarefactory-project.io/) uses OpenStack ironic and [diskimage-builder](https://docs.openstack.org/diskimage-builder/latest/), but diskimage-builder also doesn't have the ISO -> image conversion feature
