### ISSUE TITLE
Failed to Build Custom Ubuntu Cloud Image

### ISSUE THREAD

**Issue by justinwallis** [canonical/packer-maas#93]
Makefile:24: custom-cloudimg.tar.gz] Error 1

serveradmin@maas:~/packer-maas/ubuntu$ sudo make custom-cloudimg.tar.gz PACKER_LOG=1
sudo rm -f -rf output-* custom-*.gz
sudo packer init . && sudo PACKER_LOG=1 packer build -only='cloudimg.*' .
2023/02/01 22:59:10 [INFO] Packer version: 1.8.5 [go1.18.9 linux amd64]
2023/02/01 22:59:10 [TRACE] discovering plugins in /usr/bin
2023/02/01 22:59:10 [TRACE] discovering plugins in /root/.config/packer/plugins
2023/02/01 22:59:10 [DEBUG] Discovered plugin: qemu = /root/.config/packer/plugins/github.com/hashicorp/qemu/packer-plugin-qemu_v1.0.9_x5.0_linux_amd64
2023/02/01 22:59:10 [INFO] found external [-packer-default-plugin-name-] builders from qemu plugin
2023/02/01 22:59:10 [TRACE] discovering plugins in .
2023/02/01 22:59:10 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 22:59:10 [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/02/01 22:59:10 [WARN] Config file doesn't exist: /root/.packerconfig
2023/02/01 22:59:10 [INFO] Setting cache directory: /root/.cache/packer
2023/02/01 22:59:10 [TRACE] listing potential installations for "github.com/hashicorp/qemu" that match "~> 1.0". plugingetter.ListInstallationsOptions{FromFolders:[]string{"/usr/bin/packer", ".", "/root/.config/packer/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"amd64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0xc000187100)}}}}
2023/02/01 22:59:10 [TRACE] Found the following "github.com/hashicorp/qemu" installations: [{/root/.config/packer/plugins/github.com/hashicorp/qemu/packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 v1.0.9}]
2023/02/01 22:59:10 [INFO] found external [-packer-default-plugin-name-] builders from qemu plugin
2023/02/01 22:59:10 [TRACE] validateValue: not active for https_proxy, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for ssh_password, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for filename, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for kernel, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for flat_filename, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for headless, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for customize_script, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for http_directory, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for http_proxy, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for ubuntu_series, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for architecture, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for no_proxy, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for ssh_username, so skipping
2023/02/01 22:59:10 [TRACE] validateValue: not active for ssh_ubuntu_password, so skipping
2023/02/01 22:59:10 [TRACE] Starting internal plugin packer-builder-null
2023/02/01 22:59:10 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-builder-null"}
2023/02/01 22:59:10 Waiting for RPC address for: /usr/bin/packer
2023/02/01 22:59:11 packer-builder-null plugin: [INFO] Packer version: 1.8.5 [go1.18.9 linux amd64]
2023/02/01 22:59:11 packer-builder-null plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 22:59:11 packer-builder-null plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/02/01 22:59:11 packer-builder-null plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2023/02/01 22:59:11 packer-builder-null plugin: [INFO] Setting cache directory: /root/.cache/packer
2023/02/01 22:59:11 packer-builder-null plugin: args: []string{"packer-builder-null"}
2023/02/01 22:59:11 packer-builder-null plugin: Plugin address: unix /tmp/packer-plugin730629675
2023/02/01 22:59:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin730629675
2023/02/01 22:59:11 packer-builder-null plugin: Waiting for connection...
2023/02/01 22:59:11 packer-builder-null plugin: Serving a plugin connection...
2023/02/01 22:59:11 [TRACE] Starting internal plugin packer-provisioner-shell-local
2023/02/01 22:59:11 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-shell-local"}
2023/02/01 22:59:11 Waiting for RPC address for: /usr/bin/packer
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: [INFO] Packer version: 1.8.5 [go1.18.9 linux amd64]
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: [INFO] Setting cache directory: /root/.cache/packer
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: args: []string{"packer-provisioner-shell-local"}
2023/02/01 22:59:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin1446554703
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: Plugin address: unix /tmp/packer-plugin1446554703
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: Waiting for connection...
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: Serving a plugin connection...
2023/02/01 22:59:11 [TRACE] Starting external plugin /root/.config/packer/plugins/github.com/hashicorp/qemu/packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 start builder -packer-default-plugin-name-
2023/02/01 22:59:11 Starting plugin: /root/.config/packer/plugins/github.com/hashicorp/qemu/packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 []string{"/root/.config/packer/plugins/github.com/hashicorp/qemu/packer-plugin-qemu_v1.0.9_x5.0_linux_amd64", "start", "builder", "-packer-default-plugin-name-"}
2023/02/01 22:59:11 Waiting for RPC address for: /root/.config/packer/plugins/github.com/hashicorp/qemu/packer-plugin-qemu_v1.0.9_x5.0_linux_amd64
2023/02/01 22:59:11 Received unix RPC address for /root/.config/packer/plugins/github.com/hashicorp/qemu/packer-plugin-qemu_v1.0.9_x5.0_linux_amd64: addr is /tmp/packer-plugin3244714285
2023/02/01 22:59:11 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:11 Plugin address: unix /tmp/packer-plugin3244714285
2023/02/01 22:59:11 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:11 Waiting for connection...
2023/02/01 22:59:11 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:11 Serving a plugin connection...
2023/02/01 22:59:11 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:11 [TRACE] starting builder -packer-default-plugin-name-
2023/02/01 22:59:11 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:11 use detected accelerator: tcg
2023/02/01 22:59:11 [TRACE] Starting internal plugin packer-provisioner-shell
2023/02/01 22:59:11 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-shell"}
2023/02/01 22:59:11 Waiting for RPC address for: /usr/bin/packer
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] Packer version: 1.8.5 [go1.18.9 linux amd64]
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] Setting cache directory: /root/.cache/packer
2023/02/01 22:59:11 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2023/02/01 22:59:11 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin1626014604
2023/02/01 22:59:11 packer-provisioner-shell plugin: Waiting for connection...
2023/02/01 22:59:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin1626014604
2023/02/01 22:59:11 packer-provisioner-shell plugin: Serving a plugin connection...
2023/02/01 22:59:11 [TRACE] Starting internal plugin packer-provisioner-shell
2023/02/01 22:59:11 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-shell"}
2023/02/01 22:59:11 Waiting for RPC address for: /usr/bin/packer
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] Packer version: 1.8.5 [go1.18.9 linux amd64]
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] Setting cache directory: /root/.cache/packer
2023/02/01 22:59:11 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2023/02/01 22:59:11 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin877673212
2023/02/01 22:59:11 packer-provisioner-shell plugin: Waiting for connection...
2023/02/01 22:59:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin877673212
2023/02/01 22:59:11 packer-provisioner-shell plugin: Serving a plugin connection...
2023/02/01 22:59:11 [TRACE] Starting internal plugin packer-provisioner-shell
2023/02/01 22:59:11 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-shell"}
2023/02/01 22:59:11 Waiting for RPC address for: /usr/bin/packer
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] Packer version: 1.8.5 [go1.18.9 linux amd64]
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] Setting cache directory: /root/.cache/packer
2023/02/01 22:59:11 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2023/02/01 22:59:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin463586335
2023/02/01 22:59:11 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin463586335
2023/02/01 22:59:11 packer-provisioner-shell plugin: Waiting for connection...
2023/02/01 22:59:11 packer-provisioner-shell plugin: Serving a plugin connection...
2023/02/01 22:59:11 [TRACE] Starting internal plugin packer-provisioner-file
2023/02/01 22:59:11 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-file"}
2023/02/01 22:59:11 Waiting for RPC address for: /usr/bin/packer
2023/02/01 22:59:11 packer-provisioner-file plugin: [INFO] Packer version: 1.8.5 [go1.18.9 linux amd64]
2023/02/01 22:59:11 packer-provisioner-file plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 22:59:11 packer-provisioner-file plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-file plugin: [INFO] Setting cache directory: /root/.cache/packer
2023/02/01 22:59:11 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}
2023/02/01 22:59:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin1710102504
2023/02/01 22:59:11 packer-provisioner-file plugin: Plugin address: unix /tmp/packer-plugin1710102504
2023/02/01 22:59:11 packer-provisioner-file plugin: Waiting for connection...
2023/02/01 22:59:11 packer-provisioner-file plugin: Serving a plugin connection...
2023/02/01 22:59:11 [TRACE] Starting internal plugin packer-provisioner-shell
2023/02/01 22:59:11 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-shell"}
2023/02/01 22:59:11 Waiting for RPC address for: /usr/bin/packer
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] Packer version: 1.8.5 [go1.18.9 linux amd64]
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] Setting cache directory: /root/.cache/packer
2023/02/01 22:59:11 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2023/02/01 22:59:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin2959182279
2023/02/01 22:59:11 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin2959182279
2023/02/01 22:59:11 packer-provisioner-shell plugin: Waiting for connection...
2023/02/01 22:59:11 packer-provisioner-shell plugin: Serving a plugin connection...
2023/02/01 22:59:11 [TRACE] Starting internal plugin packer-provisioner-shell
2023/02/01 22:59:11 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-shell"}
2023/02/01 22:59:11 Waiting for RPC address for: /usr/bin/packer
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] Packer version: 1.8.5 [go1.18.9 linux amd64]
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2023/02/01 22:59:11 packer-provisioner-shell plugin: [INFO] Setting cache directory: /root/.cache/packer
2023/02/01 22:59:11 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2023/02/01 22:59:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin1234524249
2023/02/01 22:59:11 packer-provisioner-shell plugin: Plugin address: unix /tmp/packer-plugin1234524249
2023/02/01 22:59:11 packer-provisioner-shell plugin: Waiting for connection...
2023/02/01 22:59:11 packer-provisioner-shell plugin: Serving a plugin connection...
2023/02/01 22:59:11 [TRACE] Starting internal plugin packer-post-processor-shell-local
2023/02/01 22:59:11 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-post-processor-shell-local"}
2023/02/01 22:59:11 Waiting for RPC address for: /usr/bin/packer
2023/02/01 22:59:11 packer-post-processor-shell-local plugin: [INFO] Packer version: 1.8.5 [go1.18.9 linux amd64]
2023/02/01 22:59:11 packer-post-processor-shell-local plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/02/01 22:59:11 packer-post-processor-shell-local plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /root/.packerconfig
2023/02/01 22:59:11 packer-post-processor-shell-local plugin: [WARN] Config file doesn't exist: /root/.packerconfig
2023/02/01 22:59:11 packer-post-processor-shell-local plugin: [INFO] Setting cache directory: /root/.cache/packer
2023/02/01 22:59:11 packer-post-processor-shell-local plugin: args: []string{"packer-post-processor-shell-local"}
2023/02/01 22:59:11 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin1063530221
2023/02/01 22:59:11 packer-post-processor-shell-local plugin: Plugin address: unix /tmp/packer-plugin1063530221
2023/02/01 22:59:11 packer-post-processor-shell-local plugin: Waiting for connection...
2023/02/01 22:59:11 packer-post-processor-shell-local plugin: Serving a plugin connection...
2023/02/01 22:59:11 Build debug mode: false
cloudimg.deps.null.dependencies: output will be in this color.
2023/02/01 22:59:11 Force build: false
cloudimg.image.qemu.cloudimg: output will be in this color.

2023/02/01 22:59:11 On error: 
2023/02/01 22:59:11 Waiting on builds to complete...
2023/02/01 22:59:11 Starting build run: cloudimg.image.qemu.cloudimg
2023/02/01 22:59:11 Running builder: 
2023/02/01 22:59:11 [INFO] (telemetry) Starting builder qemu.cloudimg
2023/02/01 22:59:11 Starting build run: cloudimg.deps.null.dependencies
2023/02/01 22:59:11 Running builder: 
2023/02/01 22:59:11 [INFO] (telemetry) Starting builder null.dependencies
2023/02/01 22:59:11 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:11 Qemu path: /usr/bin/qemu-system-x86_64, Qemu Image path: /usr/bin/qemu-img
2023/02/01 22:59:11 packer-builder-null plugin: [INFO] communicator disabled, will not connect
2023/02/01 22:59:11 packer-builder-null plugin: Unable to load communicator config from state to populate provisionHookData
2023/02/01 22:59:11 packer-builder-null plugin: Running the provision hook
==> cloudimg.image.qemu.cloudimg: Retrieving ISO
2023/02/01 22:59:11 [INFO] (telemetry) Starting provisioner shell-local
==> cloudimg.image.qemu.cloudimg: Trying https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
2023/02/01 22:59:11 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:11 Acquiring lock for: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img?checksum=sha256%3A71657529fc067dbda2537762730904a68905ae1202a30ec00a645828506939df (/root/.cache/packer/4ac13ea39617f95e49eb6b13917c0e6ff190f0d5.iso.lock)
==> cloudimg.image.qemu.cloudimg: Trying https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img?checksum=sha256%3A71657529fc067dbda2537762730904a68905ae1202a30ec00a645828506939df
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: [INFO] (shell-local): Prepending inline script with #!/bin/bash -e
==> cloudimg.deps.null.dependencies: Running local shell script: /tmp/packer-shell2978727124
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: [INFO] (shell-local): starting local command: /bin/sh -c PACKER_BUILDER_TYPE='null' PACKER_BUILD_NAME='dependencies'  /tmp/packer-shell2978727124
2023/02/01 22:59:11 packer-provisioner-shell-local plugin: [INFO] (shell-local communicator): Executing local shell command [/bin/sh -c PACKER_BUILDER_TYPE='null' PACKER_BUILD_NAME='dependencies'  /tmp/packer-shell2978727124]
==> cloudimg.deps.null.dependencies: /tmp/packer-shell2978727124: line 3: cloud-localds: command not found
2023/02/01 22:59:11 [INFO] (telemetry) ending shell-local
2023/02/01 22:59:11 packer-builder-null plugin: Unable to load communicator config from state to populate provisionHookData
==> cloudimg.deps.null.dependencies: Provisioning step had errors: Running the cleanup provisioner, if present...
2023/02/01 22:59:11 [INFO] (telemetry) ending null.dependencies
Build 'cloudimg.deps.null.dependencies' errored after 21 milliseconds 779 microseconds: Script exited with non-zero exit status: 127. Allowed exit codes are: [0]
==> cloudimg.image.qemu.cloudimg: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img?checksum=sha256%3A71657529fc067dbda2537762730904a68905ae1202a30ec00a645828506939df => /root/.cache/packer/4ac13ea39617f95e49eb6b13917c0e6ff190f0d5.iso
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Leaving retrieve loop for ISO
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 No floppy files specified. Floppy disk will not be made.
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 No CD files specified. CD disk will not be made.
==> cloudimg.image.qemu.cloudimg: Creating required virtual machine disks
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 [INFO] Creating disk with Path: output-cloudimg/packer-cloudimg and Size: 4G
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Executing qemu-img: []string{"create", "-f", "qcow2", "-b", "/root/.cache/packer/4ac13ea39617f95e49eb6b13917c0e6ff190f0d5.iso", "-F", "qcow2", "-F", "qcow2", "output-cloudimg/packer-cloudimg", "4G"}
==> cloudimg.image.qemu.cloudimg: Resizing hard drive...
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 stdout: Formatting 'output-cloudimg/packer-cloudimg', fmt=qcow2 size=4294967296 backing_file=/root/.cache/packer/4ac13ea39617f95e49eb6b13917c0e6ff190f0d5.iso backing_fmt=qcow2 cluster_size=65536 lazy_refcounts=off refcount_bits=16
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 stderr:
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Executing qemu-img: []string{"resize", "-f", "qcow2", "output-cloudimg/packer-cloudimg", "4G"}
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 stdout: Image resized.
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 stderr:
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Found available port: 8063 on IP: 0.0.0.0
==> cloudimg.image.qemu.cloudimg: Starting HTTP server on port 8063
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Looking for available communicator (SSH, WinRM, etc) port between 2222 and 4444
==> cloudimg.image.qemu.cloudimg: Found port for communicator (SSH, WinRM, etc): 3695.
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Found available port: 3695 on IP: 127.0.0.1
==> cloudimg.image.qemu.cloudimg: Looking for available port between 5900 and 6000 on 127.0.0.1
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Looking for available port between 5900 and 6000 on 127.0.0.1
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Found available port: 5945 on IP: 127.0.0.1
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Found available VNC port: 5945 on IP: 127.0.0.1
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Qemu --version output: QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.24)
==> cloudimg.image.qemu.cloudimg: Starting VM, booting disk image
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Qemu version: 4.2.1
    cloudimg.image.qemu.cloudimg: view the screen of the VM, connect via VNC without a password to
    cloudimg.image.qemu.cloudimg: vnc://127.0.0.1:5945
    cloudimg.image.qemu.cloudimg: The VM will be run headless, without a GUI. If you want to
    cloudimg.image.qemu.cloudimg: view the screen of the VM, connect via VNC without a password to
    cloudimg.image.qemu.cloudimg: vnc://127.0.0.1:5945
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Qemu Builder has no floppy files, not attaching a floppy.
==> cloudimg.image.qemu.cloudimg: Overriding default Qemu arguments with qemuargs template option...
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Executing /usr/bin/qemu-system-x86_64: []string{"-cpu", "host", "-device", "virtio-gpu-pci", "-device", "virtio-net,netdev=user.0", "-drive", "if=pflash,format=raw,id=ovmf_code,readonly=on,file=/usr/share/OVMF/OVMF_CODE.fd", "-drive", "if=pflash,format=raw,id=ovmf_vars,file=OVMF_VARS.fd", "-drive", "file=output-cloudimg/packer-cloudimg,format=qcow2", "-drive", "file=seeds-cloudimg.iso,format=raw", "-boot", "c", "-vnc", "127.0.0.1:45", "-machine", "ubuntu,accel=kvm", "-name", "packer-cloudimg", "-netdev", "user,id=user.0,hostfwd=tcp::3695-:22", "-m", "2048M", "-smp", "2"}
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Started Qemu. Pid: 31645
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 Qemu stderr: qemu-system-x86_64: -drive file=seeds-cloudimg.iso,format=raw: Could not open 'seeds-cloudimg.iso': No such file or directory
==> cloudimg.image.qemu.cloudimg: Error launching VM: Qemu failed to start. Please run with PACKER_LOG=1 to get more info.
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 failed to unlock port lockfile: close tcp 127.0.0.1:5945: use of closed network connection
2023/02/01 22:59:15 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/02/01 22:59:15 failed to unlock port lockfile: close tcp 127.0.0.1:3695: use of closed network connection
==> cloudimg.image.qemu.cloudimg: Deleting output directory...
Build 'cloudimg.image.qemu.cloudimg' errored after 3 seconds 340 milliseconds: Build was halted.

==> Wait completed after 3 seconds 340 milliseconds

==> Some builds didn't complete successfully and had errors:
--> cloudimg.deps.null.dependencies: Script exited with non-zero exit status: 127. Allowed exit codes are: [0]
--> cloudimg.image.qemu.cloudimg: Build was halted.

==> Builds finished but no artifacts were created.
2023/02/01 22:59:15 [INFO] (telemetry) ending qemu.cloudimg
==> Wait completed after 3 seconds 340 milliseconds
2023/02/01 22:59:15 machine readable: error-count []string{"2"}
==> Some builds didn't complete successfully and had errors:
2023/02/01 22:59:15 machine readable: cloudimg.deps.null.dependencies,error []string{"Script exited with non-zero exit status: 127. Allowed exit codes are: [0]"}
2023/02/01 22:59:15 machine readable: cloudimg.image.qemu.cloudimg,error []string{"Build was halted."}
==> Builds finished but no artifacts were created.
2023/02/01 22:59:15 [INFO] (telemetry) Finalizing.
2023/02/01 22:59:15 waiting for all plugin processes to complete...
2023/02/01 22:59:15 /usr/bin/packer: plugin process exited
2023/02/01 22:59:15 /usr/bin/packer: plugin process exited
2023/02/01 22:59:15 /usr/bin/packer: plugin process exited
2023/02/01 22:59:15 /usr/bin/packer: plugin process exited
2023/02/01 22:59:15 /root/.config/packer/plugins/github.com/hashicorp/qemu/packer-plugin-qemu_v1.0.9_x5.0_linux_amd64: plugin process exited
2023/02/01 22:59:15 /usr/bin/packer: plugin process exited
2023/02/01 22:59:15 /usr/bin/packer: plugin process exited
2023/02/01 22:59:15 /usr/bin/packer: plugin process exited
2023/02/01 22:59:15 /usr/bin/packer: plugin process exited
2023/02/01 22:59:15 /usr/bin/packer: plugin process exited
make: *** [Makefile:24: custom-cloudimg.tar.gz] Error 1
serveradmin@maas:~/packer-maas/ubuntu$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
serveradmin@maas:~/packer-maas/ubuntu$ ls
Makefile      packages                           ubuntu-lvm.pkr.hcl
OVMF_VARS.fd  scripts                            user-data-cloudimg
README.md     ubuntu-cloudimg.pkr.hcl            user-data-flat
http          ubuntu-cloudimg.variables.pkr.hcl  user-data-lvm
meta-data     ubuntu-flat.pkr.hcl                variables.pkr.hcl

**Comment by justinwallis** [comment]
Not sure why it puts lines through some of that

**Comment by alexsander-souza** [comment]
you are missing the `cloud-image-utils` package, please check the pre-requisites in README.md
