### ISSUE TITLE
Centos 7 hangs at 'Performing post-installation setup tasks'

### ISSUE THREAD

**Issue by adnanfaridi** [canonical/packer-maas#95]
Hello

The make process for Centos 7 hangs at the last step and then eventually reaches the 1 hour execution time. 

Installing btrfs-progs (321/328)n-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/03/04 11:14:54 Qemu stdout:
Installing xfsprogs (322/328)ugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/03/04 11:14:56 Qemu stdout:
Installing efibootmgr (323/328)in-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/03/04 11:14:58 Qemu stdout:
Installing libsysfs (324/328)ugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/03/04 11:14:58 Qemu stdout:
Installing dosfstools (325/328)in-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/03/04 11:14:59 Qemu stdout:
Installing bridge-utils (326/328)-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/03/04 11:14:59 Qemu stdout:
Installing grub2-efi-x64-modules (327/328)0.9_x5.0_linux_amd64 plugin: 2023/03/04 11:15:00 Qemu stdout:
Installing rootfiles (328/328)gin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/03/04 11:15:04 Qemu stdout:
Performing post-installation setup tasks1.0.9_x5.0_linux_amd64 plugin: 2023/03/04 11:15:04 Qemu stdout:

2023/03/04 11:08:54 packer-plugin-qemu_v1.0.9_x5.0_linux_amd64 plugin: 2023/03/04 11:08:54 Qemu stdout:
og  4:storage-log  5:program-log

Thank You

**Comment by SK1Y101** [comment]
Closing this as we've managed to build centos7 images recently,
@adnanfaridi can you confirm/deny whether latest repo state works for you?
