### ISSUE TITLE
make custom-ubuntu.tar.gz fails when there are no custom packages

### ISSUE THREAD

**Issue by don** [canonical/packer-maas#99]
`make custom-ubuntu.tar.gz` fails to build when there aren't any custom packages

```
$ make custom-ubuntu.tar.gz 
sudo rm -f -rf output-* custom-*.gz
tar czf packages/custom-packages.tar.gz -C packages 
tar: Cowardly refusing to create an empty archive
Try 'tar --help' or 'tar --usage' for more information.
make: *** [Makefile:39: packages/custom-packages.tar.gz] Error 2
```

One work around is to running packer manually
```
sudo packer init .
sudo PACKER_LOG=1 packer build -only=qemu.flat .
```

Another work around is to drop a deb file into ubuntu/packages before building

**Comment by troyanov** [comment]
Hi @don 

Can you please check if https://github.com/canonical/packer-maas/pull/102 solves the issue for you?
